name: restorecoffeecreek
favicon: null
layout_spectrum: 0.7505
typography_spectrum: 0.65596
title: restore coffee creek
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#6e777d'
    - '#24251b'
    - '#cec5ba'
    - '#94a172'
  brandStrength: 0.06259653577581048
  lightness: 0.9978057767730206
  saturation: 0.8668107194826007
  rhythmicContrast: 0.4247914159204811
purpose: []
